runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
- url: /welcome
  script: welcome.php
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico